api_platform:
    title: 'Mon application Api plateform'
    description: 'pour sentrainer et tester de nouvelles choses'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
